# Generated by Django 5.0.3 on 2024-03-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render_deploy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
